### ISSUE TITLE
The required climate data is not present or configured. Either?

### ISSUE THREAD

**Issue by Jacksonmrodrigues** [GlobalEcologyLab/PaleoView#6]
Hi,

Thank you for sharing this fantastic tool.

I am trynig to learn how to handle it but I got a problem.
By trying to reproduced exactly the same as in user guide I got the following error.

A box pops up with a message.

The required climate data is not present or configured. Either:
*Download the required climate data
*Configure the local directory for existeing data
*Configure the URL of remote data (slower for ongoing use)

------------------
* My data is downloaded and stored in a folder in my desktop.
* it is configured as suggested in user guide
* not applicable

Could someone give some support ? 
It is my first touch on paleoview, so I do not know what is wrong.

Thank you,

Cheers

Jackson

**Comment by Jacksonmrodrigues** [comment]
![PaleoView Error](https://user-images.githubusercontent.com/13141074/56459142-ea952380-6365-11e9-9988-d814a973e191.png)

**Comment by seanhaythorne** [comment]
Hi Jackson,
I assume the tool is working for other time intervals (yes?).
The reason for the error is that because the interval (15,000-14,800 BP) has a window of 30 years, the tool is attempting to fetch data from 15,015-14,785 BP. It expects to find the 15,015-15,000 in the mean_temperature-22000BP-15000BP.nc file, which is not present in your directory list.
If you download the mean_temperature-22000BP-15000BP.nc file, the tool should work for those settings.
Best regards,
Sean
